// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';

// Fallback values for development (Lasy preview)
const FALLBACK_SUPABASE_URL = "https://jqpiqnjxakwusblqddoq.supabase.co";
const FALLBACK_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxcGlxbmp4YWt3dXNibHFkZG9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Mjc5MDUsImV4cCI6MjA3MzAwMzkwNX0.HmcZFDPET_6l4dK9xAuwTDB-EioA8RpMHMBi3caKy5o";

// Environment variables (for production deployment)
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || FALLBACK_SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || FALLBACK_SUPABASE_ANON_KEY;

// Lazy-loaded Supabase client
let supabaseClient: SupabaseClient | null = null;

function getSupabase(): SupabaseClient {
  if (!supabaseClient) {
    if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
      throw new Error(
        'Missing Supabase environment variables. Please check your .env.local file.'
      );
    }
    
    supabaseClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
      auth: {
        autoRefreshToken: true,
        persistSession: typeof window !== 'undefined', // Only persist in browser
      },
    });
  }
  
  return supabaseClient;
}

// Export both the function and a direct instance for convenience
export const supabase = getSupabase();
export { getSupabase };

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
// or
// import { getSupabase } from "@/integrations/supabase/client";
// const supabase = getSupabase();